### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by gtrdlr** [lwangenheim/pw_analysis#1]
Tried multiple time on multiple machines, yet keep receiving the same error. I've tried full potfile and a potfile limited to only a single hashtype. I've also tried hashlists that include usernames and hashlists that only include the hash. Same error...

All files follow the standard 'username':'hash' or 'hash':'plaintext' format. Also tried using 'strings' to ensure nothing weird with the files... Thoughts?

Thanks!

![image](https://user-images.githubusercontent.com/25823963/60038616-d67de300-9682-11e9-827c-a6192f1fcd4e.png)

**Comment by lwangenheim** [comment]
Hi, Let me dig into this a bit and I'll get back to you. Also thanks for trying it out!

**Comment by lwangenheim** [comment]
After discussing the issue with the user, it was determined that the cause was plaintext passwords containing a colon. This breaks the parser function currently. Fix incoming.

**Comment by lwangenheim** [comment]
This has been fixed (finally)
